### ISSUE TITLE
appscode/stash-postgres not found in repo

### ISSUE THREAD

**Issue by pdstefan** [stashed/catalog#6]
Hi, 

Interested in trying out stashed with the postgres plugin. 
When using the "Install only YAML" method, helm errors out 
```
root@vm-bilbo:~# curl -fsSL https://github.com/stashed/catalog/raw/master/deploy/script.sh | bash
"appscode" has been added to your repositories
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "appscode" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Error: chart "stash-postgres" matching version "11.2" not found in appscode index. (try 'helm repo update'). no chart name found
```

Looked at the cached repo contents, no catalog matching "stash-postgres" exists. 
Kindly take a look at the repo or updade the docs if necessary. 

Thanks. 
S.

**Comment by tamalsaha** [comment]
Stash plugins has been published with Stash v0.9.0-rc.1 release https://appscode.com/products/stash/v0.9.0-rc.1/addons/postgres/ . Thanks for your patience !
